### ISSUE TITLE
Implement approval and backup logic

### ISSUE THREAD

**Issue by lucasmm96** [lucasmm96/message-manager-api#6]
## Description 
- Implement rules for `admin-users` and `non-admin-users`
 - All actions (`Insert`, `Update`, `Delete`) need to be backed up.
 - Data changes from `non-admin-users` will require `admin-users` approval to be taken in place.
 - New user creation will require `admin-users` approval to be taken in place when its access level is admin.

## Tasks:

- [x] Create models for new tables `pending-message` and `pending-user`
- [x] Organize a set of routes for `user` and `admin`
- [x] Define pattern for route names
- [x] Refactor user routes
- [x] Refactor admin routes
- [x] Apply db changes on both tables `pending-message` and `message` when the user is admin (user routes)
  - [x] Add Message
  - [x] Update Message
  - [x] Delete Message
- [x] Create an admin route for pending message rejections.
- [x] Create features (similar to the message ones) to manage user creation requests
  - [x] Adjust the `pending-user` model
  - [x] Set all user creation to go straight to the `pending-user` collection (it will be waiting for admin approval)
  - Set method to:
    - [x] Approve new user
    - [x] Reject new user
    - [x] Remove user

**Comment by lucasmm96** [comment]
## Task list:

- [Refactor admin routes](https://github.com/users/lucasmm96/projects/1/views/1?pane=issue&itemId=29993948)
